tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/backend.omnisight.co/fullchain.pem
        keyFile: /etc/letsencrypt/live/backend.omnisight.co/privkey.pem
  options:
    default:
      minVersion: VersionTLS12
